name: deploy-to-server
on:
  push:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_DIR: /var/www/ds_bussiness

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Correr pruebas
        run: |
          echo "Probando..."

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Copy to server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
              --exclude='.git' \
              --exclude='.github' \
              --exclude='node_modules' \
              --exclude='*.md' \
              --exclude='LICENSE' \
              . ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
